"""7 stage definitions: each stage carries a fixed genome stem and 3
candidates that vary one or two axes.  Mirrors the .aice exactly.
"""

from __future__ import annotations


COMMON_REPRO = {
    "seed": 42,
    "corpus_pinned": True,
    "uses_external_api": False,
    "single_script": True,
}


def _candidate(name: str, style: str, **overrides):
    g = dict(COMMON_REPRO)
    g["name"] = name
    g["style"] = style
    g.update(overrides)
    return g


STAGES = [
    {
        "name": "NGramFreq",
        "branch": "main",
        "param_class": "32K",
        "real_train": True,
        "candidates": [
            _candidate("N1", "char_bigram_laplace",
                      model_family="ngram_count", n=2, alpha=1.0,
                      param_class="32K", engine="numpy_only",
                      training_paradigm="count_normalize",
                      deps=["python>=3.11"]),
            _candidate("N2", "char_trigram_with_backoff",
                      model_family="ngram_count", n=3, alpha=0.5,
                      param_class="32K", engine="numpy_only",
                      training_paradigm="count_normalize",
                      deps=["python>=3.11"]),
            _candidate("N3", "byte_unigram_only",
                      model_family="ngram_count", n=1, alpha=1.0,
                      param_class="32K", engine="numpy_only",
                      training_paradigm="count_normalize",
                      deps=["python>=3.11"]),
        ],
    },
    {
        "name": "CharRNN",
        "branch": "main",
        "param_class": "100K",
        "real_train": False,
        "candidates": [
            _candidate("R1", "single_layer_GRU_tied",
                      model_family="char_rnn", cell="GRU",
                      embed_dim=64, hidden_dim=128, layers=1, vocab=256,
                      ctx=128, tied_embedding=True, dropout=0,
                      param_class="100K", engine="pytorch_cpu",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="implicit_recurrence",
                      normalization="none", regularization="none",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("R2", "single_layer_LSTM_untied",
                      model_family="char_rnn", cell="LSTM",
                      embed_dim=64, hidden_dim=128, layers=1, vocab=256,
                      ctx=128, tied_embedding=False, dropout=0,
                      param_class="100K", engine="pytorch_cpu",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="implicit_recurrence",
                      normalization="none", regularization="none",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("R3", "GRU_with_input_dropout",
                      model_family="char_rnn", cell="GRU",
                      embed_dim=64, hidden_dim=128, layers=1, vocab=256,
                      ctx=128, tied_embedding=True, dropout=0.1,
                      param_class="100K", engine="pytorch_cpu",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="implicit_recurrence",
                      normalization="none", regularization="dropout",
                      deps=["python>=3.11", "pytorch==2.x"]),
        ],
    },
    {
        "name": "TinyTransformer",
        "branch": "main",
        "param_class": "1M",
        "real_train": False,
        "candidates": [
            _candidate("T1", "depth1_h4_d128_rope_rmsnorm",
                      model_family="single_block_transformer",
                      depth=1, n_heads=4, d_model=128, ffn_mult=4,
                      vocab=256, ctx=128, tied_embedding=True,
                      param_class="1M", engine="pytorch_cpu_or_mps",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="rope", normalization="rmsnorm",
                      regularization="none",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("T2", "depth1_h4_d128_learned_layernorm",
                      model_family="single_block_transformer",
                      depth=1, n_heads=4, d_model=128, ffn_mult=4,
                      vocab=256, ctx=128, tied_embedding=True,
                      param_class="1M", engine="pytorch_cpu_or_mps",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="learned_absolute",
                      normalization="layernorm", regularization="none",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("T3", "depth1_h2_d96_rope",
                      model_family="single_block_transformer",
                      depth=1, n_heads=2, d_model=96, ffn_mult=4,
                      vocab=256, ctx=128, tied_embedding=True,
                      param_class="1M", engine="pytorch_cpu_or_mps",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="rope", normalization="rmsnorm",
                      regularization="none",
                      deps=["python>=3.11", "pytorch==2.x"]),
        ],
    },
    {
        "name": "ImprovedMicroGPT",
        "branch": "improvement_path",
        "param_class": "3M",
        "real_train": False,
        "candidates": [
            _candidate("G1", "depth4_h4_d192_drop01_kvcache",
                      model_family="multi_block_transformer",
                      depth=4, n_heads=4, d_model=192, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("G2", "depth8_h4_d160_drop005_kvcache",
                      model_family="multi_block_transformer",
                      depth=8, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.05,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("G3", "depth4_h8_d192_grouped_kvcache",
                      model_family="multi_block_transformer",
                      depth=4, n_heads=8, d_model=192, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="maximum_likelihood_sgd",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
        ],
    },
    {
        "name": "DistilledMicro",
        "branch": "improvement_path",
        "param_class": "3M",
        "real_train": False,
        "candidates": [
            _candidate("DI1", "soft_label_T2_alpha05",
                      model_family="distilled_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="distillation",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("DI2", "soft_label_plus_intermediate_match",
                      model_family="distilled_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="distillation",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      steps=4500,
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("DI3", "data_only_distill",
                      model_family="distilled_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="distillation",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
        ],
    },
    {
        "name": "PreferenceTuned",
        "branch": "alignment_path",
        "param_class": "3M",
        "real_train": False,
        "candidates": [
            _candidate("PT1", "pairs_top_vs_bottom_full_finetune",
                      model_family="preference_tuned_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="distillation_plus_dpo",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("PT2", "kl_anchored_full_finetune",
                      model_family="preference_tuned_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="distillation_plus_dpo",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("PT3", "three_axis_separate_lora",
                      model_family="preference_tuned_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="distillation_plus_dpo",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache_plus_int8",
                      deps=["python>=3.11", "pytorch==2.x"]),
        ],
    },
    {
        "name": "SemiAutoEvolve",
        "branch": "join",
        "param_class": "3M",
        "real_train": False,
        "candidates": [
            _candidate("SE1", "model_drafts_three_mutations",
                      model_family="self_evolving_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="self_proposed_mutation",
                      self_evolution="model_proposes_three_mutations",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("SE2", "model_writes_full_next_stage",
                      model_family="self_evolving_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="self_proposed_mutation",
                      self_evolution="model_writes_full_stage",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
            _candidate("SE3", "model_critiques_then_proposes",
                      model_family="self_evolving_compact",
                      depth=4, n_heads=4, d_model=160, ffn_mult=4,
                      vocab=256, ctx=256, tied_embedding=True, dropout=0.1,
                      param_class="3M", engine="pytorch_mps",
                      training_paradigm="self_proposed_mutation",
                      self_evolution="model_critiques_then_proposes",
                      positional="rope", normalization="rmsnorm",
                      regularization="dropout",
                      inference_optimization="kv_cache",
                      deps=["python>=3.11", "pytorch==2.x"]),
        ],
    },
]
