// Generated by aipl_to_promela.py from PhilosophersOrdered
// Verifies the LTL property: <> all_phils_done.

#define MAX_Q 8
#define QSIZE 8

#define N_FORK 3
#define N_PHIL 3

mtype = { m_granted, m_init, m_release, m_request, m_try_eat };

chan mb_fork[N_FORK] = [QSIZE] of {mtype, byte, byte, byte, byte};
chan mb_phil[N_PHIL] = [QSIZE] of {mtype, byte, byte, byte, byte};

byte fork_held[N_FORK];
byte fork_queue_arr[N_FORK * MAX_Q];
byte fork_queue_len[N_FORK];
byte fork_qstart[N_FORK];
byte phil_lo[N_PHIL];
byte phil_hi[N_PHIL];
byte phil_meals[N_PHIL];
byte phil_got_lo[N_PHIL];
byte phil_done[N_PHIL];

proctype Fork(byte self_idx) {
    mtype meth; byte sender; byte a0; byte a1; byte a2;
    byte nxt;
end_Fork:
    do
    :: mb_fork[self_idx] ? meth, sender, a0, a1, a2 ->
        if
        :: meth == m_request ->
            if
            :: ((fork_held[self_idx] == 0)) ->
                fork_held[self_idx] = 1;
                mb_phil[sender] ! m_granted, self_idx, 0, 0, 0;
            :: else ->
                fork_queue_arr[self_idx*MAX_Q + fork_queue_len[self_idx]] = sender;
                fork_queue_len[self_idx]++;
            fi;
        :: meth == m_release ->
            if
            :: ((fork_qstart[self_idx] < fork_queue_len[self_idx])) ->
                nxt = fork_queue_arr[self_idx*MAX_Q + (fork_qstart[self_idx])];
                fork_qstart[self_idx] = (fork_qstart[self_idx] + 1);
                mb_phil[nxt] ! m_granted, self_idx, 0, 0, 0;
            :: else ->
                fork_held[self_idx] = 0;
            fi;
        :: else -> skip;
        fi;
    od;
}

proctype Phil(byte self_idx) {
    mtype meth; byte sender; byte a0; byte a1; byte a2;
end_Phil:
    do
    :: mb_phil[self_idx] ? meth, sender, a0, a1, a2 ->
        if
        :: meth == m_init ->
            phil_lo[self_idx] = a0;
            phil_hi[self_idx] = a1;
            phil_meals[self_idx] = a2;
            mb_phil[self_idx] ! m_try_eat, self_idx, 0, 0, 0;
        :: meth == m_try_eat ->
            if
            :: ((phil_meals[self_idx] <= 0)) ->
                phil_done[self_idx] = 1;
            :: else ->
                phil_got_lo[self_idx] = 0;
                mb_fork[phil_lo[self_idx]] ! m_request, self_idx, 0, 0, 0;
            fi;
        :: meth == m_granted ->
            if
            :: ((phil_got_lo[self_idx] == 0)) ->
                phil_got_lo[self_idx] = 1;
                mb_fork[phil_hi[self_idx]] ! m_request, self_idx, 0, 0, 0;
            :: else ->
                phil_meals[self_idx] = (phil_meals[self_idx] - 1);
                phil_got_lo[self_idx] = 0;
                mb_fork[phil_lo[self_idx]] ! m_release, self_idx, 0, 0, 0;
                mb_fork[phil_hi[self_idx]] ! m_release, self_idx, 0, 0, 0;
                if
                :: ((phil_meals[self_idx] > 0)) ->
                    mb_phil[self_idx] ! m_try_eat, self_idx, 0, 0, 0;
                :: else ->
                    phil_done[self_idx] = 1;
                fi;
            fi;
        :: else -> skip;
        fi;
    od;
}

init {
    atomic {
        run Fork(0);
        run Fork(1);
        run Fork(2);
        run Phil(0);
        run Phil(1);
        run Phil(2);
        mb_phil[0] ! m_init, 255, 0, 1, 1;
        mb_phil[1] ! m_init, 255, 1, 2, 1;
        mb_phil[2] ! m_init, 255, 0, 2, 1;
    }
}

#define all_phils_done (phil_done[0] == 1 && phil_done[1] == 1 && phil_done[2] == 1)

ltl progress { <> all_phils_done }
