"""Phase 5: emit an AIPL orchestrator program from the .ga.json IR.

The generated `.abcl` is targeted at the Python runtime in
`src/python-aipl/`. It exercises the actor framework end-to-end:

  Coordinator  --now-->  Generator       (mutate / cross / seed)
  Coordinator  --now-->  Evaluator
                          --future->  Reviewer1 (ai_call optional)
                          --future->  Reviewer2 (ai_call optional)
                          --future->  Reviewer3 (ai_call optional)
                          (await all, aggregate)
  Coordinator  --send-->  EliteMap      (record champion per cell)
  Coordinator  --send-->  Lineage       (record every individual)

In Phase 5 the reviewer scoring is deterministic so the run is
reproducible without burning AI tokens. Phase 6 flips the
`use_ai` flag and parses real ai_call replies."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _abcl_string(s: str) -> str:
    """Quote and escape for AIPL string literals."""
    return (
        '"'
        + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        + '"'
    )


# Per-task ideal genome fragments. Single source of truth — import from
# evaluator.py to avoid drift between Python and AIPL codegen.
from .evaluator import TASK_PROFILES


def _profile_string(profile: dict[str, str]) -> str:
    return "|".join(f"{k}={v}" for k, v in profile.items())


def _axis_table(axes: dict[str, list[str]]) -> str:
    """Encode the schema axes as 'axis:v1,v2|axis:v1,v2|...'."""
    return "|".join(f"{axis}:{','.join(values)}" for axis, values in axes.items())


def generate_program(spec: dict[str, Any], schema: dict[str, Any]) -> str:
    name = spec["name"]
    task_desc = spec.get("task", "")
    axes = schema["axes"]
    cell_axes = spec["search"]["cell_axes"]
    seed_count = int(spec["search"]["seed_count"])
    generations = int(spec["search"]["generations"])
    rng_seed = int(spec["search"].get("rng_seed", 42))
    eval_tasks = spec["evaluation"]["tasks"]
    reviewers = spec["evaluation"]["reviewers"]

    axis_table = _axis_table(axes)
    axes_csv = ",".join(axes.keys())
    cell_axes_csv = ",".join(cell_axes)

    # Build per-task dispatch with inline profile literals (no self-method
    # call to avoid the actor's re-entrant deadlock).
    task_dispatch = []
    for i, t in enumerate(eval_tasks):
        prof_lit = _abcl_string(_profile_string(TASK_PROFILES.get(t, {})))
        prefix = "if" if i == 0 else "else if"
        task_dispatch.append(f'    {prefix} (task_name == "{t}") {{ reply({prof_lit}); }}')
    if eval_tasks:
        task_dispatch.append('    else { reply(""); }')
    task_dispatch_body = "\n".join(task_dispatch) if task_dispatch else '    reply("");'
    task_profiles_block = "  // task profiles inlined into get(); no separate methods."

    # reviewers list (top-level decls). use_ai pulled from spec.
    use_ai_flag = 1 if spec.get("evaluation", {}).get("use_ai") else 0
    reviewer_decls = []
    for i, r in enumerate(reviewers, start=1):
        persona = r.get("persona", "")
        weight = float(r.get("weight", 1.0 / max(1, len(reviewers))))
        reviewer_decls.append(
            f'var rev{i} = new Reviewer({_abcl_string(r["name"])}, '
            f'{_abcl_string(persona)}, {use_ai_flag}, {weight}, util, digits);'
        )
    reviewer_decls_block = "\n".join(reviewer_decls) if reviewer_decls else "// no reviewers configured"

    n_reviewers = len(reviewers)
    reviewer_init_args = ", ".join(f"rev{i}" for i in range(1, n_reviewers + 1))
    reviewer_count = max(1, n_reviewers)
    if not reviewers:
        reviewer_init_args = "0, 0, 0"

    eval_tasks_csv = ",".join(eval_tasks)

    out_lineage_path = f"out/{name}.abcl_lineage.json"

    # Compose the full AIPL source.
    return f"""// Generated by aice-evolution-v2/src/aipl_codegen.py from {name}
// Pipeline: seed (random genome per axis) -> evolve via mutate/cross
// -> per-task scoring across reviewers -> elite map per cell
// -> dump lineage as JSON for the Python report pipeline.
//
// Run:
//   AIPL_AI_PROVIDER=mock /usr/bin/python3 src/python-aipl/aipl_main.py {name}.abcl
//
// Reviewers compute deterministic scores in Phase 5. Setting use_ai=1
// (Phase 6) makes them call ai_call_with_system per scoring request.

// --------------------------------------------------------------------
// Util — shared string + genome helpers
// --------------------------------------------------------------------

class Util {{
  method count_csv(csv) {{
    if (str_len(csv) == 0) {{ reply(0); }}
    else {{
      var n = 1;
      var s = csv;
      var done = 0;
      while (done == 0) do {{
        var c = str_index(s, ",");
        if (c < 0) {{
          done = 1;
        }} else {{
          n = n + 1;
          s = str_sub(s, c + 1);
        }}
      }}
      reply(n);
    }}
  }}

  method nth_csv(csv, n) {{
    var i = 0;
    var s = csv;
    while (i < n) do {{
      var c = str_index(s, ",");
      if (c < 0) {{
        s = "";
        i = n;
      }} else {{
        s = str_sub(s, c + 1);
        i = i + 1;
      }}
    }}
    var c2 = str_index(s, ",");
    if (c2 < 0) {{ reply(s); }}
    else {{ reply(str_sub(s, 0, c2)); }}
  }}

  method axis_values(table, axis) {{
    // table is "axis:v1,v2|axis:v1,v2|..."
    var key = axis + ":";
    var idx = str_index(table, key);
    if (idx < 0) {{ reply(""); }}
    else {{
      var start = idx + str_len(key);
      var rest = str_sub(table, start);
      var bar = str_index(rest, "|");
      if (bar < 0) {{ reply(rest); }}
      else {{ reply(str_sub(rest, 0, bar)); }}
    }}
  }}

  method get_axis(genome, axis) {{
    var key = axis + "=";
    var idx = str_index(genome, key);
    if (idx < 0) {{ reply(""); }}
    else {{
      var start = idx + str_len(key);
      var rest = str_sub(genome, start);
      var bar = str_index(rest, "|");
      if (bar < 0) {{ reply(rest); }}
      else {{ reply(str_sub(rest, 0, bar)); }}
    }}
  }}

  method set_axis(genome, axis, value) {{
    var key = axis + "=";
    var idx = str_index(genome, key);
    if (idx < 0) {{
      if (str_len(genome) == 0) {{ reply(key + value); }}
      else {{ reply(genome + "|" + key + value); }}
    }} else {{
      var prefix = str_sub(genome, 0, idx);
      var after = idx + str_len(key);
      var rest = str_sub(genome, after);
      var bar = str_index(rest, "|");
      if (bar < 0) {{ reply(prefix + key + value); }}
      else {{
        var suffix = str_sub(rest, bar);
        reply(prefix + key + value + suffix);
      }}
    }}
  }}

  // parse_score(s): scan s for the first decimal number 0.0..1.0 and
  // return it as a float. "75" / "0.75" / "score: 0.7 (good)" all work.
  // Calls digits.val(c) on a peer actor (no self-call).
  method parse_score(s, digits) {{
    var n = str_len(s);
    var i = 0;
    var found = 0;
    var first_digit = -1;
    while (found == 0) do {{
      if (i >= n) {{ found = 2; }}
      else {{
        var c = str_sub(s, i, i + 1);
        var d = now digits.val(c);
        if (d >= 0) {{
          first_digit = d;
          found = 1;
        }} else {{
          i = i + 1;
        }}
      }}
    }}
    if (found == 2) {{ reply(0.5); }}
    else {{
      var int_part = first_digit;
      i = i + 1;
      var done_int = 0;
      while (done_int == 0) do {{
        if (i >= n) {{ done_int = 1; }}
        else {{
          var c2 = str_sub(s, i, i + 1);
          var d2 = now digits.val(c2);
          if (d2 >= 0) {{
            int_part = int_part * 10 + d2;
            i = i + 1;
          }} else {{ done_int = 1; }}
        }}
      }}
      var frac = 0.0;
      var div = 1.0;
      if (i < n) {{
        var dotc = str_sub(s, i, i + 1);
        if (dotc == ".") {{
          i = i + 1;
          var done_frac = 0;
          while (done_frac == 0) do {{
            if (i >= n) {{ done_frac = 1; }}
            else {{
              var c3 = str_sub(s, i, i + 1);
              var d3 = now digits.val(c3);
              if (d3 >= 0) {{
                div = div * 10.0;
                frac = frac + (d3 + 0.0) / div;
                i = i + 1;
              }} else {{ done_frac = 1; }}
            }}
          }}
        }}
      }}
      var v = (int_part + 0.0) + frac;
      // Tolerate "75" meaning 75% (no decimal).
      if (v > 1.0) {{ v = v / 100.0; }}
      if (v < 0.0) {{ v = 0.0; }}
      if (v > 1.0) {{ v = 1.0; }}
      reply(v);
    }}
  }}
}}

// --------------------------------------------------------------------
// DigitOps — peer actor for parse_score so Util can avoid self-call.
// --------------------------------------------------------------------

class DigitOps {{
  method val(c) {{
    if (c == "0") {{ reply(0); }}
    else if (c == "1") {{ reply(1); }}
    else if (c == "2") {{ reply(2); }}
    else if (c == "3") {{ reply(3); }}
    else if (c == "4") {{ reply(4); }}
    else if (c == "5") {{ reply(5); }}
    else if (c == "6") {{ reply(6); }}
    else if (c == "7") {{ reply(7); }}
    else if (c == "8") {{ reply(8); }}
    else if (c == "9") {{ reply(9); }}
    else {{ reply(-1); }}
  }}
}}

// --------------------------------------------------------------------
// Worker — compound operations that orchestrate Util/Evaluator/Profiles.
// Lives in its own actor so its callers (e.g. Coordinator) can use `now`
// without re-entering themselves.
// --------------------------------------------------------------------

class Worker {{
  var util = 0;
  var evaluator = 0;
  var profiles = 0;

  method init(u, e, p) {{
    util = u;
    evaluator = e;
    profiles = p;
  }}

  method compute_cell(genome, cell_axes_csv) {{
    var n = now util.count_csv(cell_axes_csv);
    var i = 0;
    var out = "";
    while (i < n) do {{
      var axis = now util.nth_csv(cell_axes_csv, i);
      var v = now util.get_axis(genome, axis);
      if (i == 0) {{ out = axis + "=" + v; }}
      else {{ out = out + "|" + axis + "=" + v; }}
      i = i + 1;
    }}
    reply(out);
  }}

  method compute_score(genome, task_csv) {{
    var n = now util.count_csv(task_csv);
    var i = 0;
    var sum = 0.0;
    while (i < n) do {{
      var task = now util.nth_csv(task_csv, i);
      var prof = now profiles.get(task);
      var s = now evaluator.score_for_task(genome, prof);
      sum = sum + s;
      i = i + 1;
    }}
    var avg = sum;
    if (n > 0) {{ avg = sum / (n + 0.0); }}
    reply(avg);
  }}
}}

// --------------------------------------------------------------------
// Generator — seed / mutate / crossover
// --------------------------------------------------------------------

class Generator {{
  var util = 0;
  var axes_csv = "";
  var values_table = "";

  method init(u, axes, values) {{
    util = u;
    axes_csv = axes;
    values_table = values;
  }}

  method seed() {{
    var n_axes = now util.count_csv(axes_csv);
    var i = 0;
    var g = "";
    while (i < n_axes) do {{
      var axis = now util.nth_csv(axes_csv, i);
      var vals = now util.axis_values(values_table, axis);
      var n_vals = now util.count_csv(vals);
      var v = now util.nth_csv(vals, random(n_vals));
      if (i == 0) {{ g = axis + "=" + v; }}
      else {{ g = g + "|" + axis + "=" + v; }}
      i = i + 1;
    }}
    reply(g);
  }}

  method mutate(parent) {{
    var n_axes = now util.count_csv(axes_csv);
    var idx = random(n_axes);
    var axis = now util.nth_csv(axes_csv, idx);
    var vals = now util.axis_values(values_table, axis);
    var n_vals = now util.count_csv(vals);
    var v = now util.nth_csv(vals, random(n_vals));
    var child = now util.set_axis(parent, axis, v);
    reply(child);
  }}

  method cross(a, b) {{
    var n_axes = now util.count_csv(axes_csv);
    var i = 0;
    var child = "";
    while (i < n_axes) do {{
      var axis = now util.nth_csv(axes_csv, i);
      var src = a;
      if (random(2) == 1) {{ src = b; }}
      var v = now util.get_axis(src, axis);
      if (i == 0) {{ child = axis + "=" + v; }}
      else {{ child = child + "|" + axis + "=" + v; }}
      i = i + 1;
    }}
    reply(child);
  }}
}}

// --------------------------------------------------------------------
// Reviewer — one ai_call_with_system per score request (Phase 6),
//            deterministic scoring (Phase 5).
// --------------------------------------------------------------------

class Reviewer {{
  var name = "";
  var persona = "";
  var use_ai = 0;
  var weight = 0.0;
  var util = 0;
  var digits = 0;

  method init(n, p, u, w, util_actor, digits_actor) {{
    name = n;
    persona = p;
    use_ai = u;
    weight = w;
    util = util_actor;
    digits = digits_actor;
  }}

  method score(genome, task_profile) {{
    if (use_ai == 1) {{
      var prompt = "評価対象の遺伝子: " + genome +
                   "\\n理想プロファイル: " + task_profile +
                   "\\n\\nこのプロファイルに対する適合度を 0.0 から 1.0 の単一の decimal number で返してください。説明禁止。数値1つだけ。";
      var ai_text = ai_call_with_system(persona, prompt);
      var ai_score = now util.parse_score(ai_text, digits);
      reply(ai_score);
    }} else {{
    // Deterministic: fraction of profile axes the genome matches.
    var matches = 0;
    var total = 0;
    var rest = task_profile;
    while (str_len(rest) > 0) do {{
      var bar = str_index(rest, "|");
      var pair = "";
      if (bar < 0) {{
        pair = rest;
        rest = "";
      }} else {{
        pair = str_sub(rest, 0, bar);
        rest = str_sub(rest, bar + 1);
      }}
      var eq = str_index(pair, "=");
      if (eq >= 0) {{
        var axis = str_sub(pair, 0, eq);
        var want = str_sub(pair, eq + 1);
        var key = axis + "=";
        var gidx = str_index(genome, key);
        if (gidx >= 0) {{
          var gstart = gidx + str_len(key);
          var grest = str_sub(genome, gstart);
          var gbar = str_index(grest, "|");
          var got = "";
          if (gbar < 0) {{ got = grest; }}
          else {{ got = str_sub(grest, 0, gbar); }}
          if (got == want) {{ matches = matches + 1; }}
        }}
        total = total + 1;
      }}
    }}
    var s = 0.0;
    if (total > 0) {{ s = (matches + 0.0) / (total + 0.0); }}
    reply(s);
    }}
  }}

  method get_weight() {{ reply(weight); }}
}}

// --------------------------------------------------------------------
// Evaluator — fans out reviewer scoring with `future`, awaits, aggregates
// --------------------------------------------------------------------

class Evaluator {{
  var r1 = 0;
  var r2 = 0;
  var r3 = 0;
  var n_revs = 0;

  method init(rev1, rev2, rev3, n) {{
    r1 = rev1;
    r2 = rev2;
    r3 = rev3;
    n_revs = n;
  }}

  method score_for_task(genome, profile) {{
    if (n_revs >= 1) {{
      var f1 = future r1.score(genome, profile);
      var s1 = await(f1);
      var f2 = future r2.score(genome, profile);
      var s2 = await(f2);
      var f3 = future r3.score(genome, profile);
      var s3 = await(f3);
      var w1 = now r1.get_weight();
      var w2 = now r2.get_weight();
      var w3 = now r3.get_weight();
      var combined = s1 * w1 + s2 * w2 + s3 * w3;
      reply(combined);
    }} else {{
      reply(0.0);
    }}
  }}
}}

// --------------------------------------------------------------------
// EliteMap — cell -> champion id mapping with parallel arrays
// --------------------------------------------------------------------

class EliteMap {{
  var cells = [];
  var ids = [];
  var scores = [];
  var genomes = [];

  method propose(cell, ind_id, genome, score) {{
    var n = array_len(cells);
    var i = 0;
    var idx = -1;
    while (i < n) do {{
      if (array_get(cells, i) == cell) {{
        idx = i;
        i = n;
      }} else {{
        i = i + 1;
      }}
    }}
    if (idx < 0) {{
      array_push(cells, cell);
      array_push(ids, ind_id);
      array_push(scores, score);
      array_push(genomes, genome);
      reply(1);
    }} else {{
      var existing = array_get(scores, idx);
      if (score > existing) {{
        array_set(ids, idx, ind_id);
        array_set(scores, idx, score);
        array_set(genomes, idx, genome);
        reply(1);
      }} else {{
        reply(0);
      }}
    }}
  }}

  method size() {{ reply(array_len(cells)); }}

  method sample_random_genome() {{
    var n = array_len(cells);
    if (n == 0) {{ reply(""); }}
    else {{ reply(array_get(genomes, random(n))); }}
  }}

  method best_summary(top_k) {{
    var n = array_len(cells);
    var i = 0;
    var out = "";
    while (i < n) do {{
      var line = "  cell=" + array_get(cells, i) +
                 "  score=" + array_get(scores, i) +
                 "  id=" + array_get(ids, i);
      if (i == 0) {{ out = line; }}
      else {{ out = out + "\\n" + line; }}
      i = i + 1;
    }}
    reply(out);
  }}
}}

// --------------------------------------------------------------------
// Lineage — append-only individual record
// --------------------------------------------------------------------

class Lineage {{
  var ids = [];
  var genomes = [];
  var parents = [];
  var scores = [];
  var generations = [];
  var operators = [];
  var cells = [];

  method add(id, genome, parent, score, gen, op, cell) {{
    array_push(ids, id);
    array_push(genomes, genome);
    array_push(parents, parent);
    array_push(scores, score);
    array_push(generations, gen);
    array_push(operators, op);
    array_push(cells, cell);
    reply(array_len(ids));
  }}

  method dump(path) {{
    var n = array_len(ids);
    var i = 0;
    var out = "[\\n";
    while (i < n) do {{
      // score gets a trailing "0" so 0.0 stringifies to "0.00"
      // (Python runtime emits "0." which would be invalid JSON).
      var entry = "  {{\\"id\\":\\"" + array_get(ids, i) + "\\"," +
                  "\\"genome\\":\\"" + array_get(genomes, i) + "\\"," +
                  "\\"parent\\":\\"" + array_get(parents, i) + "\\"," +
                  "\\"score\\":" + array_get(scores, i) + "0," +
                  "\\"generation\\":" + array_get(generations, i) + "," +
                  "\\"operator\\":\\"" + array_get(operators, i) + "\\"," +
                  "\\"cell\\":\\"" + array_get(cells, i) + "\\"}}";
      if (i < n - 1) {{ out = out + entry + ",\\n"; }}
      else {{ out = out + entry + "\\n"; }}
      i = i + 1;
    }}
    out = out + "]\\n";
    write_file(path, out);
    reply(n);
  }}
}}

// --------------------------------------------------------------------
// TaskProfiles — embedded per-task ideal genome fragments
// --------------------------------------------------------------------

class TaskProfiles {{
{task_profiles_block}

  method get(task_name) {{
{task_dispatch_body}
  }}
}}

// --------------------------------------------------------------------
// Coordinator — main loop
// --------------------------------------------------------------------

class Coordinator {{
  var util = 0;
  var generator = 0;
  var evaluator = 0;
  var elite = 0;
  var lineage = 0;
  var profiles = 0;
  var worker = 0;

  var seed_count = {seed_count};
  var generations = {generations};
  var cell_axes_csv = {_abcl_string(cell_axes_csv)};
  var task_csv = {_abcl_string(eval_tasks_csv)};
  var next_id = 0;

  method init(u, g, e, em, lg, tp, w) {{
    util = u;
    generator = g;
    evaluator = e;
    elite = em;
    lineage = lg;
    profiles = tp;
    worker = w;
  }}

  method run() {{
    print("=== {name} (AIPL — Actor-based Intelligent Parallel Language — orchestrator) ===");
    print("seed_count=" + seed_count + "  generations=" + generations);

    // Phase 1: seed
    var i = 0;
    while (i < seed_count) do {{
      var g = now generator.seed();
      next_id = next_id + 1;
      var id = "I" + next_id;
      var cell = now worker.compute_cell(g, cell_axes_csv);
      var score = now worker.compute_score(g, task_csv);
      send lineage.add(id, g, "", score, 0, "seed", cell);
      send elite.propose(cell, id, g, score);
      i = i + 1;
    }}
    print("[seed] elite cells filled: " + (now elite.size()));

    // Phase 2: evolution
    var gen = 1;
    while (gen <= generations) do {{
      var parent = now elite.sample_random_genome();
      var size = now elite.size();
      var do_cross = 0;
      if (random(10) < 3) {{
        if (size >= 2) {{ do_cross = 1; }}
      }}
      var child = "";
      var op = "";
      if (do_cross == 1) {{
        var partner = now elite.sample_random_genome();
        child = now generator.cross(parent, partner);
        op = "uniform_crossover";
      }} else {{
        child = now generator.mutate(parent);
        op = "axis_resample";
      }}
      next_id = next_id + 1;
      var cid = "I" + next_id;
      var ccell = now worker.compute_cell(child, cell_axes_csv);
      var cscore = now worker.compute_score(child, task_csv);
      send lineage.add(cid, child, "", cscore, gen, op, ccell);
      send elite.propose(ccell, cid, child, cscore);
      gen = gen + 1;
    }}

    print("[done] cells filled: " + (now elite.size()));
    print(now elite.best_summary(5));

    var n = now lineage.dump({_abcl_string(out_lineage_path)});
    print("[lineage] wrote " + n + " individuals to {out_lineage_path}");
  }}
}}

// --------------------------------------------------------------------
// Bootstrap (top-level)
// --------------------------------------------------------------------

var util = new Util();
var digits = new DigitOps();
var generator = new Generator(util, {_abcl_string(axes_csv)}, {_abcl_string(axis_table)});
var elite = new EliteMap();
var lineage = new Lineage();
var profiles = new TaskProfiles();

{reviewer_decls_block}
var eval_actor = new Evaluator({reviewer_init_args}, {reviewer_count});
var worker = new Worker(util, eval_actor, profiles);
var coord = new Coordinator(util, generator, eval_actor, elite, lineage, profiles, worker);
send coord.run();
"""


def write_program(spec: dict[str, Any], schema: dict[str, Any], out_dir: str | Path) -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    target = out / f"{spec['name']}.abcl"
    target.write_text(generate_program(spec, schema), encoding="utf-8")
    return target
