(ocamllex (modules lexer))
(ocamlyacc (modules parser))

(library
 (name abcllib)
 (wrapped false)
 (modules
  ast
  location
  types
  typing_env
  infer
  typecheck
  sdl_helper
  remote_client
  parser
  lexer
  eval_thread
  compiler
  web_gateway)
 (flags (:standard -w -a))
 (libraries tsdl threads unix))

(executable
 (name repl_thread)
 (modules repl_thread)
 (flags (:standard -w -a))
 (libraries abcllib tsdl threads unix))
