(ocamllex (modules lexer))
(ocamlyacc (modules parser))

(library
 (name abcllib)
 (wrapped false)
 (modules
  ast
  location
  types
  typing_env
  infer
  typecheck
  sdl_helper
  remote_client
  parser
  lexer
  eval_thread
  compiler
  c_translator
  web_gateway
  ai)
 (flags (:standard -w -a))
 (libraries tsdl threads unix))

(executable
 (name repl_thread)
 (modules repl_thread)
 (flags (:standard -w -a))
 (libraries abcllib tsdl threads unix))

(executable
 (name tui_ide)
 (modules tui_ide)
 (flags (:standard -w -a))
 (libraries unix threads))

(executable
 (name gui_ide)
 (modules gui_ide gui_font)
 (flags (:standard -w -a))
 (libraries abcllib tsdl threads unix))

(executable
 (name abcl2c)
 (modules abcl2c)
 (flags (:standard -w -a))
 (libraries abcllib))
